### ISSUE TITLE
Why did you use this method for finding this syscall table

### ISSUE THREAD

**Issue by dnoiz1** [0xSinner/SinKit#2]
Just curious, but there are other methods to do this
Could you explain why you used such a heavy handed way to do it?
Or does this defeat a certain mitigation I might not be aware of?

https://github.com/0xSinner/SinKit/blob/master/hidden.c#L28-L46

Thanks,
Love your work.

**Comment by dnoiz1** [comment]
did you close this issue because you ripped this repo and you actually have no idea how it works?

**Comment by nopn0p** [comment]
Why do you insist on uploading what clearly isn't your code to github?

**Comment by netspooky** [comment]
alert(1)
